---
- name: Install Python 3 and pip
  apt:
    name: python3-pip
    state: present

- name: Install Flask
  pip:
    name: flask
    state: present

- name: Create Flask application directory
  file:
    path: /home/yillkid/flask-app
    state: directory

- name: Create Flask application file
  copy:
    content: |
      from flask import Flask

      app = Flask(__name__)

      @app.route('/')
      def hello():
          return 'Hello, Flask!'

      if __name__ == '__main__':
          app.run(debug=True)
    dest: /home/yillkid/flask-app/app.py

- name: Start Flask application
  command: python3 /home/yillkid/falsk-app/app.py
