name: Daily Ansible Playbook

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip3 install ansible

      - name: Create playbook file
        copy:
          content: |
            ---
            - hosts: localhost
              name: beta-eid signin
              tasks:
                - name: API request
                  uri:
                    method: POST
                    url: https://beta-eid-backend.townway.com.tw/accounts/signin
                    body_format: form-multipart
                    body:
                      email: "ntc@gmail.com"
                      password: ${{ NTCPW }}
                   status_code: 200
                 register: result
                 failed_when: result.status not in [200]
          ...
          dest: /home/yillkid/eid-signin.yaml

      - name: Run Ansible playbook
        run: ansible-playbook /home/yillkid/eid-signin.yaml
